import { useState } from 'react';
import { fa } from '../content/fa';

type LogoProps = {
  variant: 'stacked' | 'horizontal';
  className?: string;
  /** True only for the hero mark, which is above the fold on every screen. */
  priority?: boolean;
};

/**
 * Logo masters are supplied by the founders and live in brand/ — they are brand
 * assets, not something this codebase draws. If the generated file is ever
 * missing, this falls back to a plain wordmark so the page still reads as
 * finished rather than broken.
 */
/** Generated by scripts/build-images.mjs from the masters in brand/. */
const SOURCES = {
  stacked: { src: '/brand/bizynex-stacked.png', width: 384, height: 331 },
  horizontal: { src: '/brand/bizynex-horizontal.png', width: 448, height: 102 },
} as const;

export const Logo = ({ variant, className, priority = false }: LogoProps) => {
  const [missing, setMissing] = useState(false);
  const source = SOURCES[variant];

  if (missing) {
    return (
      <span
        dir="ltr"
        lang="en"
        className={`inline-block font-semibold tracking-tight text-navy-800 ${className ?? ''}`}
      >
        Bizynex
      </span>
    );
  }

  return (
    <img
      src={source.src}
      width={source.width}
      height={source.height}
      alt={fa.ui.brandName}
      className={className}
      loading={priority ? 'eager' : 'lazy'}
      decoding={priority ? 'sync' : 'async'}
      onError={() => setMissing(true)}
    />
  );
};
