/**
 * Bakes the page into dist/index.html so the content is readable before any
 * JavaScript runs.
 *
 * This is not a framework and it does not need to become one. The site is one
 * static page: render it once, paste the markup in, delete the server build.
 * Everything after that is the same client-side app hydrating over it.
 */
import { readFile, writeFile, rm } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const distDir = join(root, 'dist');
const serverDir = join(distDir, 'server');

const { render, jsonLdScript, siteUrl } = await import(
  pathToFileURL(join(serverDir, 'entry-server.js')).href
);

const template = await readFile(join(distDir, 'index.html'), 'utf8');

/**
 * Two substitutions, both of which must land. A silent miss here ships a page
 * with no content or no structured data and nothing would notice until a
 * crawler did, so each one throws rather than warns.
 */
const substitutions = [
  ['<div id="root"></div>', () => `<div id="root">${render()}</div>`],
  ['<!--seo-jsonld-->', () => jsonLdScript],
];

let html = template;

for (const [placeholder, build] of substitutions) {
  if (!html.includes(placeholder)) {
    throw new Error(`prerender: could not find ${placeholder} in dist/index.html`);
  }
  html = html.replace(placeholder, build);
}

await writeFile(join(distDir, 'index.html'), html, 'utf8');

/**
 * The sitemap, generated rather than committed.
 *
 * It used to live in public/ with a `<lastmod>` typed by hand, which is a date
 * that is correct exactly once. A date that never moves tells a crawler the
 * site never moves, and a wrong date is worse than none — Google weighs
 * `lastmod` only for sites whose `lastmod` has proved trustworthy.
 *
 * The build date is a proxy for the content date, and the trade-off is real:
 * redeploying for a CSS tweak bumps it too. For a three-person team shipping a
 * one-page site that is close enough to always mean "we changed something",
 * and the alternative — hashing the copy against a committed stamp file — is
 * more machinery than the accuracy is worth. Revisit that if deploys ever get
 * frequent and content changes do not.
 *
 * `changefreq` and `priority` are gone. Google has stated it ignores both, and
 * a field nobody reads is a field that will eventually be wrong.
 */
const lastmod = new Date().toISOString().slice(0, 10);

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/prerender.mjs. Do not edit; edit the script. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${siteUrl}/</loc>
    <lastmod>${lastmod}</lastmod>
  </url>
</urlset>
`;

await writeFile(join(distDir, 'sitemap.xml'), sitemap, 'utf8');

await rm(serverDir, { recursive: true, force: true });

console.log(`prerender: dist/index.html is the full page, sitemap.xml stamped ${lastmod}`);
